# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.16

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/rausa/Software/lib/CGNSMod

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/rausa/Software/lib/CGNSMod

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/rausa/Software/lib/CGNSMod/CMakeFiles /home/rausa/Software/lib/CGNSMod/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/rausa/Software/lib/CGNSMod/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named main

# Build rule for target.
main: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 main
.PHONY : main

# fast build rule for target.
main/fast:
	$(MAKE) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/build
.PHONY : main/fast

#=============================================================================
# Target rules for targets named CGNSMod

# Build rule for target.
CGNSMod: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 CGNSMod
.PHONY : CGNSMod

# fast build rule for target.
CGNSMod/fast:
	$(MAKE) -f CMakeFiles/CGNSMod.dir/build.make CMakeFiles/CGNSMod.dir/build
.PHONY : CGNSMod/fast

src/cose.o: src/cose.cpp.o

.PHONY : src/cose.o

# target to build an object file
src/cose.cpp.o:
	$(MAKE) -f CMakeFiles/CGNSMod.dir/build.make CMakeFiles/CGNSMod.dir/src/cose.cpp.o
.PHONY : src/cose.cpp.o

src/cose.i: src/cose.cpp.i

.PHONY : src/cose.i

# target to preprocess a source file
src/cose.cpp.i:
	$(MAKE) -f CMakeFiles/CGNSMod.dir/build.make CMakeFiles/CGNSMod.dir/src/cose.cpp.i
.PHONY : src/cose.cpp.i

src/cose.s: src/cose.cpp.s

.PHONY : src/cose.s

# target to generate assembly for a file
src/cose.cpp.s:
	$(MAKE) -f CMakeFiles/CGNSMod.dir/build.make CMakeFiles/CGNSMod.dir/src/cose.cpp.s
.PHONY : src/cose.cpp.s

tools/main.o: tools/main.cpp.o

.PHONY : tools/main.o

# target to build an object file
tools/main.cpp.o:
	$(MAKE) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/tools/main.cpp.o
.PHONY : tools/main.cpp.o

tools/main.i: tools/main.cpp.i

.PHONY : tools/main.i

# target to preprocess a source file
tools/main.cpp.i:
	$(MAKE) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/tools/main.cpp.i
.PHONY : tools/main.cpp.i

tools/main.s: tools/main.cpp.s

.PHONY : tools/main.s

# target to generate assembly for a file
tools/main.cpp.s:
	$(MAKE) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/tools/main.cpp.s
.PHONY : tools/main.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... rebuild_cache"
	@echo "... main"
	@echo "... edit_cache"
	@echo "... CGNSMod"
	@echo "... src/cose.o"
	@echo "... src/cose.i"
	@echo "... src/cose.s"
	@echo "... tools/main.o"
	@echo "... tools/main.i"
	@echo "... tools/main.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

